# Generated by Django 4.0.1 on 2022-01-18 02:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarURL', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=5)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swipehomeapi.appuser')),
                ('userTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swipehomeapi.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientId', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('timestamp', models.IntegerField()),
                ('unread', models.BooleanField(default='true')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swipehomeapi.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000000)])),
                ('beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('baths_full', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='swipehomeapi.address')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swipehomeapi.appuser')),
                ('userTypeId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swipehomeapi.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Fave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=5)),
                ('beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('baths', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20000000)])),
                ('photo', models.CharField(max_length=150)),
                ('timestamp', models.IntegerField()),
                ('houseId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swipehomeapi.house')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swipehomeapi.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='userTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='types', to='swipehomeapi.usertype'),
        ),
    ]
