# Generated by Django 4.0.1 on 2022-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipehomeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='firstTimeUser',
            field=models.CharField(default=True, max_length=5),
            preserve_default=False,
        ),
    ]
