# Generated by Django 4.0.1 on 2022-01-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipehomeapi', '0002_appuser_firsttimeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fave',
            name='property_id',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
