# Generated by Django 4.0.1 on 2022-01-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swipehomeapi', '0003_fave_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='photos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='swipehomeapi.photo'),
            preserve_default=False,
        ),
    ]
