# Generated by Django 4.0.1 on 2022-01-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swipehomeapi', '0004_photo_house_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fave',
            name='houseId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='swipehomeapi.house'),
        ),
    ]
